
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'LINE NUMBER PAPER PENprogram : statement_liststatement_list : statement statement_liststatement_list : statementstatement : PAPER NUMBERstatement : PEN NUMBERstatement : LINE NUMBER NUMBER NUMBER NUMBER'
    
_lr_action_items = {'PAPER':([0,3,8,9,13,],[4,4,-4,-5,-6,]),'PEN':([0,3,8,9,13,],[5,5,-4,-5,-6,]),'LINE':([0,3,8,9,13,],[6,6,-4,-5,-6,]),'$end':([1,2,3,7,8,9,13,],[0,-1,-3,-2,-4,-5,-6,]),'NUMBER':([4,5,6,10,11,12,],[8,9,10,11,12,13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement_list':([0,3,],[2,7,]),'statement':([0,3,],[3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement_list','program',1,'p_program','parser.py',10),
  ('statement_list -> statement statement_list','statement_list',2,'p_statement_list_multiple','parser.py',14),
  ('statement_list -> statement','statement_list',1,'p_statement_list_single','parser.py',18),
  ('statement -> PAPER NUMBER','statement',2,'p_statement_paper','parser.py',22),
  ('statement -> PEN NUMBER','statement',2,'p_statement_pen','parser.py',26),
  ('statement -> LINE NUMBER NUMBER NUMBER NUMBER','statement',5,'p_statement_line','parser.py',30),
]
